version: '3'
services:
  server:
    image: nginx
    container_name: PhoenixCounselling
    ports:
        - "127.0.0.1:80:80"
    volumes:
        - ./app:/usr/share/nginx/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/logs:/var/log/nginx